#!/bin/bash
echo "\"(Ôo)'" \
#!/bin/bash
echo "Hello, World"
#!/bin/bash
echo "Hello, World"
© 2022 GitHub, Inc.
Terms
Privacy
clear
#!/bin/bash
echo "Hello, World"
chmod u+x 0-hello_world
#!/bin/bash
echo "Hello, World"
